### ISSUE TITLE
Animate toggleChildren?

### ISSUE THREAD

**Issue by nicknikolov** [constantin-p/cp-react-tree-table#29]
What would be the best strategy to do this in your view?
Thanks!

**Comment by constantin-p** [comment]
Hi @nicknikolov,

You can animate the toggle (or anything in the parent node cells) just by using CSS, but unfortunately, there's currently no out-of-the-box support for animating row insertion/deletion corresponding to expanding/collapsing nodes.

![animated-toggle](https://user-images.githubusercontent.com/22005076/84053180-da993280-a9b1-11ea-9d2d-2c402f9755f1.gif)

[`JSFiddle Demo`](http://jsfiddle.net/constantin_p/hb8597sr/), relevant lines:

```css
.cp_tree-table .cp_tree-table_cell .toggle-button:not(:disabled)::after {
  /* ... */
  transform: translateY(-50%) rotate(0);
  /* ... */
  transition: transform 0.15s ease;
}

.cp_tree-table .cp_tree-table_cell .toggle-button.expanded:not(:disabled)::after {
  transform: translateY(-50%) rotate(90deg);
}
```
